### ISSUE TITLE
Assets de cenário - EPIC

### ISSUE THREAD

**Issue by Jubabibou** [buff-buff-studio/Solis#417]
@Jubabibou (exportar)

- [x] Fliperama
- [x] Latas de tinta
- [x] Rolo de tinta
- [x] Base rolo de tinta
- [x] Painel energia
- [x] Galinhas e patos (3 modelos, 6 texturas)
- [x] Lâmpada redonda

@Bozzipontojpg (fazer e exportar)

- [x] Porco rigado e texturizado
- [x] Portão garagem animado
- [ ] Modelo ovelha
- [ ] Modelo celeiro (exterior)

@HelenaRMP (exportar e finalizar)

- [x] rádio de pilha
- [ ] cesto de bolas 
- [ ] bola de basquete 
- [ ] Aro de basquete 
- [ ] Caminhonete
- [x] Mesa com blueprints
- [x] Cadeira escritório
- [x] Lâmpada Led 
- [x] Jacaré Hidráulico 
- [x] Elevador hidráulico

@LucasQuinino 

- [x] trator
